version: 2
jobs:
  build:
    working_directory: /tmp
    docker:
      - image: circleci/node:8
    steps:
      - run: mkdir -p workspace && cd workspace
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm run lint
      - run: npm run build
      - run: npm run test
      - run: npm run generate
      - persist_to_workspace:
        root: workspace
        paths:
            - echo-output
      - store_artifacts:
          path: /tmp/dist
  deploy:
    docker:
      - image: circleci/node:8
    steps:
      - attach_workspace:
        at: /tmp/workspace
      - run: git config user.name $GITHUB_NAME
      - run: git config user.email $GITHUB_EMAIL
      - run: ls -lrt
workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
